### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by mb236** [SvenEV/WinSwag#15]
I followed your instructions for the installation of the app, but it fails with the following error message: 
"Fehler beim Installieren der Paketabhängigkeiten. Fordern Sie beim Entwickler ein Microsoft.VCLibs.140.00.Debug-Paket an. "

When can I expect a fix for that?

**Comment by SvenEV** [comment]
Soon™ 😉

**Comment by mb236** [comment]
🐱‍🚀

**Comment by cbruegg** [comment]
Another: `App Installer failed to install package dependencies. Ask the developer for Microsoft.NET.CoreRuntime.2.1 package. `
